DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER
(
    USER_ID  VARCHAR(255) NOT NULL,
    USER_NAME   VARCHAR(255),
    PASS_WORD   VARCHAR(255),
    CREATED_AT TIMESTAMP,
    PRIMARY KEY (USER_ID)
);


DROP TABLE IF EXISTS KOSPI_STOCK;
CREATE TABLE KOSPI_STOCK
(
    KOSPI_STOCK_ID  VARCHAR(255) NOT NULL,
    NO  VARCHAR(255) NOT NULL,
    STOCK_NAME  VARCHAR(255) NOT NULL,
    PRICE  VARCHAR(255),
    DIFF_AMOUNT  VARCHAR(255),
    DAY_RANGE  VARCHAR(255),
    PAR_VALUE  VARCHAR(255),
    MARKET_CAP  VARCHAR(255),
    NUMBER_OF_LISTED_SHARES   VARCHAR(255),
    FOREIGN_OWN_RATE   VARCHAR(255),
    PER   VARCHAR(255),
    ROE   VARCHAR(255),
    DISCUSSION_ROOM_URL   VARCHAR(255),
    PRIMARY KEY (KOSPI_STOCK_ID),
    CREATED_AT TIMESTAMP
);

DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM (
      ROOM_ID VARCHAR(255) PRIMARY KEY,
      NO VARCHAR(255),
      STOCK_NAME VARCHAR(255),
      PRICE VARCHAR(255),
      PRICE_PERCENT INT,
      PERSON_CNT INT,
      TOTAL_PERCENT INT,
      CREATED_AT TIMESTAMP
);

DROP TABLE IF EXISTS ROOM_MEMBER;
CREATE TABLE ROOM_MEMBER (
     ROOM_MEMBER_ID VARCHAR(255) PRIMARY KEY,
     ROOM_ID VARCHAR(255),
     USER_ID VARCHAR(255),
     PRICE_PERCENT INT,
     TRADING_CNT DOUBLE,
     PERSON_PERCENT INT,
     CONTRACT_CMP_YN VARCHAR(10),
     CREATED_AT TIMESTAMP
);
